version: '3'
services:
  client:
    build: client
    container_name: client
    ports:
      - '8080:80'
    networks:
      - app-network
    depends_on:
      - server
  server:
    build: server
    container_name: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://client:8080
      - JWT_SECRET=your-secure-jwt-secret-12345
      - MONGO_URI=mongodb://mongodb:27017/mern_ecommerce
      - MAILGUN_API_KEY=dummy-key
      - MAILGUN_DOMAIN=dummy-domain
    ports:
      - '3000:3000'
    volumes:
      - /home/ubuntu/mern-ecommerce/server/dist:/usr/src/app/dist
    command:
      - sh
      - -c
      - npm run seed:db admin@example.com admin123 && npm start
    depends_on:
      - mongodb
    networks:
      - app-network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
