apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: mern-server
        imagePullPolicy: Never
        env:
          - name: MONGO_URI
            value: "mongodb+srv://rayen:Bs5atsbHz2PLAQob@rayen.jim9tlg.mongodb.net/ecommerce?retryWrites=true&w=majority&appName=rayen"
          - name: JWT_SECRET
            value: "your-secure-jwt-secret-12345"
          - name: MAILGUN_API_KEY
            value: "dummy-key"
          - name: MAILGUN_DOMAIN
            value: "dummy-domain" 
        ports:
         - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
